### ISSUE TITLE
Bash Error

### ISSUE THREAD

**Issue by cyaris** [adamdehaven/fetchurls#1]
Hey Adam!

Really cool concept. Do you know what this error might mean?

fetchurls-master/fetchurls.sh: line 61: read: -i: invalid option

Thanks,
Charlie

**Comment by adamdehaven** [comment]
It's most likely related to the version of bash you're running. 

The `read -i` feature is `bash` specific, and only available in `bash` version 4.0 and above.

Hope that helps.

If you need to modify the script to work without the `-i` option, let me know.
