### ISSUE TITLE
v3.2.3 Non Interactive Mode now allowing a few attributes 

### ISSUE THREAD

**Issue by PetroLogic** [adamdehaven/fetchurls#12]
**Describe the bug**
Version v3.2.3
Non-interactive mode always overrides -f -l and -e attributes with defaults

**To Reproduce**
./fetchurls.sh -t -d http://example.com -l /tmp -f file -e "css"

Just review the troubleshooting output.

Made the following changes to correct issue.

 diff fetchurls.sh fetchurls.sh-ORIG
493c493
< elif [ -z "$USER_SAVE_LOCATION" ] && [ "$RUN_NONINTERACTIVE" -eq 1 ]; then
---
> else
508c508
< elif [ -z "$USER_FILENAME" ] && [ "$RUN_NONINTERACTIVE" -eq 1 ]; then
---
> else
521c521
< elif [ -z "$USER_EXCLUDED_EXTENTIONS" ] && [ "$RUN_NONINTERACTIVE" -eq 1 ]; then
---
> else

Thanks for your efforts.

**Comment by adamdehaven** [comment]
@PetroLogic good catch! Issue is now resolved and [available for download](https://github.com/adamdehaven/fetchurls/releases/latest). 👍
