### ISSUE TITLE
Question - fetchUrlsForDomain

### ISSUE THREAD

**Issue by usermor** [adamdehaven/fetchurls#15]
In [fetchUrlsForDomain](/adamdehaven/fetchurls/blob/master/fetchurls.sh#L344), `grep` is used to search for user exluded extensions after `wget` has downloaded the files. I couldn't see a written explanation for why filtering for extensions was done in this way, rather than filtering them using `wget --reject` or `wget --reject-regex`. Was this for reliability?

Not sure if this was the right place or way to ask, I'm very new and inexperienced. Thanks!

**Comment by adamdehaven** [comment]
To be honest, I probably just coded what what quick when I needed it. 

This is a good idea (to filter before actually downloading). I should have some in the next week to take a look and likely switch things over. I'll be sure to ping you. Thanks!

**Comment by adamdehaven** [comment]
@usermor I have updated the script to `v3.5.0` that now filters via the native `wget` `--reject-regex` flag.
Thanks for the suggestion!
