### ISSUE TITLE
Permission issue to write file

### ISSUE THREAD

**Issue by momnpophubadmin** [adamdehaven/fetchurls#4]
Hey, 

I keep getting the following errors and it never asks me for the location where i want to store. It did ask me the prompt to enter the url of the website where I wanted to fetch the urls. Not sure how to resolve the permission issue to let it write the file and ask me about the file name steps. 

```shell

#    
#    Save file to location
/Users/varunkhanduja/Desktop/fetchurls-master/fetchurls.sh: line 103: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
usage: mkdir [-pv] [-m mode] directory ...
#    
#    Save file as
/Users/varunkhanduja/Desktop/fetchurls-master/fetchurls.sh: line 110: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
#    
#    Fetching URLs for 
#    
/Users/varunkhanduja/Desktop/fetchurls-master/fetchurls.sh: line 64: /.txt: Permission denied

```

**Comment by adamdehaven** [comment]
@momnpophubadmin you're likely using an outdated version of bash (or whatever terminal shell you are running on your machine). Try upgrading to the newest version. 

If you use Git Bash, you may grab the latest version <a href="https://gitforwindows.org/" target="_blank">here</a>
