### ISSUE TITLE
Error: <domain> is unresponsive or is not a valid URL.

### ISSUE THREAD

**Issue by Lilja** [adamdehaven/fetchurls#9]
All the different domains I'm trying ends up with the error message above.

Is there a debug mode or something similar I can try out?

![image](https://user-images.githubusercontent.com/6134511/93311803-bc3fa000-f806-11ea-9af9-d92987b46574.png)

**Comment by adamdehaven** [comment]
@Lilja Good catch 👍! The script was erroneously catching some 3xx HTTP statuses in a block that terminated the script. I've made an update, and will issue a new release momentarily. 

In addition, based on the output in your screenshot, you may want to upgrade the version of `grep` on your computer to `3.1`. It looks like the version you're on likely doesn't support the `-E, --extended-regexp` flag.

**Comment by adamdehaven** [comment]
@Lilja go ahead and [grab the newest release](https://github.com/adamdehaven/fetchurls/releases/); you should be good to go :tada:
